#!/bin/bash -eu

cat <<YAML
steps:

  - name: Test
    command: ./auto/test
    agents:
      queue: cpdev:build

  - name: Build
    command: ./auto/build
    agents:
      queue: cpdev:build
YAML

if test "$BUILDKITE_BRANCH" = "master" && test "$BUILDKITE_PULL_REQUEST" = "false"; then
cat <<YAML

  - wait

  - block: OK release
    branches: master
  - name: Release docker image from master build
    branches: master
    command: ./auto/release
    artifact_paths: artifacts/docker-image.txt
    agents:
      queue: cpdev:build
YAML
fi
