#! /bin/bash -eu
#
# Publish Docker image

cd $(dirname $0)/..

REPOSITORY=registry.cowbell.realestate.com.au/cowbell/pager_duty_ctl
VERSION=$(cat version.txt)

echo "--- Check that we're releasing from master"
git fetch origin
git diff origin/master --exit-code

semantic_versions() {
  case $1 in
    *.*) printf %s "$1 $(semantic_versions ${1%\.*})" ;;
    *) printf %s "$1"
  esac
}

echo "--- Releasing Docker image"
docker build -t ${REPOSITORY}:latest .
docker push ${REPOSITORY}:latest
for version in $(semantic_versions $VERSION); do
  docker tag ${REPOSITORY}:latest ${REPOSITORY}:${version}
  docker push ${REPOSITORY}:${version}
done
mkdir -p target
DIGEST=$(docker pull ${REPOSITORY}:${VERSION} | sed -n 's/^Digest: // p')
IMAGE="${REPOSITORY}:${VERSION}@${DIGEST}"
echo "$IMAGE" > target/docker-image.txt
echo "Released as: $IMAGE"

git tag ${VERSION}
git push origin ${VERSION}
